# Generated by Django 5.1.1 on 2024-09-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_travellerinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travellerinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15, null=True),
        ),
    ]
