# Generated by Django 4.2.15 on 2024-09-04 17:07

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('traveldate', models.DateField()),
                ('time', models.TimeField()),
                ('Description', models.TextField()),
                ('cost', models.IntegerField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('people_limit', models.IntegerField()),
                ('people', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.travel')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratting', models.IntegerField(choices=[(4, '⭐⭐⭐⭐'), (3, '⭐⭐⭐'), (1, '⭐'), (2, '⭐⭐'), (5, '⭐⭐⭐⭐⭐')])),
                ('textreview', models.TextField()),
                ('reviewer', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('travelname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.travel')),
            ],
        ),
    ]
