# Generated by Django 4.2.15 on 2024-09-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ratting',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐'), (2, '⭐⭐'), (4, '⭐⭐⭐⭐'), (3, '⭐⭐⭐'), (1, '⭐')]),
        ),
    ]
