# Generated by Django 5.1.1 on 2024-09-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_review_ratting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ratting',
            field=models.IntegerField(choices=[(2, '⭐⭐'), (4, '⭐⭐⭐⭐'), (1, '⭐'), (3, '⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')]),
        ),
    ]
