# Generated by Django 5.1.1 on 2024-09-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_review_ratting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ratting',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐'), (1, '⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (2, '⭐⭐')]),
        ),
    ]
