# Generated by Django 5.1.1 on 2024-09-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_review_ratting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ratting',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (1, '⭐'), (3, '⭐⭐⭐'), (2, '⭐⭐')]),
        ),
    ]
