# Generated by Django 4.2.15 on 2024-09-04 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharetravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peoplelimit', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Maintravel', to='event.travel')),
                ('shareby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharebywho', to=settings.AUTH_USER_MODEL)),
                ('travellersgroup', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
